settings:
  title: "\uE001"
  betterhud_pointer_id: "gps_pointer"
  arrival_radius: 5.0
  update_interval_ticks: 5

messages:
  use_global_prefix: false
  started: "&a[SHK 내비게이션] {destination}(으)로 길 안내를 시작합니다."
  stopped: "&e[SHK 내비게이션] 길 안내를 중지되었습니다."
  arrived: "&a[SHK 내비게이션] 목적지({destination})에 도착했습니다!"
  different_world: "&c[SHK 내비게이션] 목적지가 다른 월드에 있어 안내를 시작할 수 없습니다."

destinations:
  apartments_a_north:
    material: COMPASS
    name: "A아파트 북쪽"
    model_name: 0
    location:
      world: "other"
      x: -1572.5
      y: 56.0
      z: 400.5

  apartments_a_south:
    material: COMPASS
    name: "A아파트 남쪽"
    model_name: 0
    location:
      world: "other"
      x: -1571.5
      y: 56.0
      z: 120.5

  apartments_b:
    material: COMPASS
    name: "B아파트"
    model_name: 0
    location:
      world: "other"
      x: -1286.5
      y: 56.0
      z: 151.5

  arts_association:
    material: COMPASS
    name: "예술협회"
    model_name: 0
    location:
      world: "other"
      x: -1572.5
      y: 56.0
      z: 718.5
      yaw: 90.0

  assembly:
    material: COMPASS
    name: "의회"
    model_name: 0
    location:
      world: "other"
      x: -917.5
      y: 56.0
      z: 429.5

  central_shopping_street:
    material: COMPASS
    name: "중앙 상가거리"
    model_name: 0
    location:
      world: "other"
      x: -1433.5
      y: 56.0
      z: 256.5

  central_square:
    material: COMPASS
    name: "중앙 광장"
    model_name: 0
    location:
      world: "other"
      x: -1447.5
      y: 55.0
      z: -32.5

  city_hall:
    material: COMPASS
    name: "시청"
    model_name: 0
    location:
      world: "other"
      x: -1444.5
      y: 59.0
      z: -202.5

  court:
    material: COMPASS
    name: "법원"
    model_name: 0
    location:
      world: "other"
      x: -917.5
      y: 56.0
      z: 650.5

  fire_agency:
    material: COMPASS
    name: "소방청"
    model_name: 0
    location:
      world: "other"
      x: -1286.5
      y: 56.0
      z: 680.5

  hall_of_fame:
    material: COMPASS
    name: "명예의 전당"
    model_name: 0
    location:
      world: "other"
      x: -1607.5
      y: 56.0
      z: 800.5

  harbor:
    material: COMPASS
    name: "항만"
    model_name: 0
    location:
      world: "other"
      x: -2081.5
      y: 56.0
      z: -833.5

  high_school:
    material: COMPASS
    name: "고등학교"
    model_name: 0
    location:
      world: "other"
      x: -1683.5
      y: 56.0
      z: 271.5

  hospital:
    material: COMPASS
    name: "병원"
    model_name: 0
    location:
      world: "other"
      x: -1091.5
      y: 56.0
      z: 686.5

  north_shopping_street:
    material: COMPASS
    name: "북쪽 상가거리"
    model_name: 0
    location:
      world: "other"
      x: -1634.5
      y: 56.0
      z: -593.5

  police_office:
    material: COMPASS
    name: "경찰청"
    model_name: 0
    location:
      world: "other"
      x: -1057.5
      y: 56.0
      z: 449.5

  prosecutors_office:
    material: COMPASS
    name: "검찰청"
    model_name: 0
    location:
      world: "other"
      x: -1218.5
      y: 56.0
      z: 463.5

  sbc:
    material: COMPASS
    name: "SBC"
    model_name: 0
    location:
      world: "other"
      x: -1322.5
      y: 56.0
      z: 710.5

  sostco:
    material: COMPASS
    name: "소스트코"
    model_name: 0
    location:
      world: "other"
      x: -901.5
      y: 56.0
      z: 295.5

  sports_complex:
    material: COMPASS
    name: "종합경기장"
    model_name: 0
    location:
      world: "other"
      x: -1006.5
      y: 56.0
      z: -201.5

  townhouse_complex:
    material: COMPASS
    name: "빌라 단지"
    model_name: 0
    location:
      world: "other"
      x: -1679.5
      y: 56.0
      z: 474.5

  train_station:
    material: COMPASS
    name: "기차역"
    model_name: 0
    location:
      world: "other"
      x: -1296.5
      y: 56.0
      z: -611.5

  university:
    material: COMPASS
    name: "대학교"
    model_name: 0
    location:
      world: "other"
      x: -1695.5
      y: 56.0
      z: -174.5

  wedding_hall:
    material: COMPASS
    name: "결혼식장"
    model_name: 0
    location:
      world: "other"
      x: -1201.5
      y: 56.0
      z: -265.5